# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqyuyKqerFQjwouI8N0RQhf0SWpZwbSc
"""

import zipfile

with zipfile.ZipFile("archive (1).zip", 'r') as zip_ref:
    zip_ref.extractall()

print("Unzipped successfully")

import pandas as pd

df = pd.read_csv("online_retail_II.csv", encoding='ISO-8859-1')

df.head()

df.columns

df = df.rename(columns={
    'Invoice': 'InvoiceNo',
    'Price': 'UnitPrice',
    'Customer ID': 'CustomerID'
})

df = df.dropna(subset=['CustomerID'])

df = df[df['Quantity'] > 0]
df = df[df['UnitPrice'] > 0]

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

df.head()

snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'count',
    'TotalPrice': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']

rfm.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

kmeans = KMeans(n_clusters=4, random_state=42)
labels = kmeans.fit_predict(rfm_scaled)

print("Silhouette Score:", silhouette_score(rfm_scaled, labels))

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
reduced = pca.fit_transform(rfm_scaled)

plt.figure(figsize=(8,6))
plt.scatter(reduced[:,0], reduced[:,1], c=labels)
plt.title("Customer Segmentation")
plt.show()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K = range(1,10)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(rfm_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,6))
plt.plot(K, inertia, 'bo-')
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.title("Elbow Method For Optimal K")
plt.show()

from sklearn.cluster import AgglomerativeClustering

hier = AgglomerativeClustering(n_clusters=4)
labels_hier = hier.fit_predict(rfm_scaled)

print("Hierarchical clustering completed")

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.8, min_samples=10)
labels_db = dbscan.fit_predict(rfm_scaled)

print("DBSCAN clustering completed")

from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(n_components=4, random_state=42)
labels_gmm = gmm.fit_predict(rfm_scaled)

print("GMM clustering completed")

rfm['Cluster'] = labels
rfm.groupby('Cluster').mean()

